In [38]:
import pywt
import numpy as np
from PIL import Image
import pandas as pd
from scipy.stats import zscore
from sklearn.metrics import mean_squared_error


def dwt_compression(data):
   
    coeffs_r = pywt.dwt2(data, 'haar')
   
    return coeffs_r


def dwt_decompress(coeff_dwt):
    return pywt.idwt2(coeff_dwt, 'haar')

In [39]:
def utf8len(s):
    return len(s.encode('utf-8'))

In [40]:
#df = pd.read_csv('/mnt/simhomes/binzc/results/1gram.csv')
df = pd.read_csv('/mnt/simhomes/binzc/results/zscore_np_20k.csv')
data=df.to_numpy()
compressed = dwt_compression(data)
print(compressed)
print(len(compressed))

(array([[1.010000e+02, 1.220000e+02, 1.330000e+02, ..., 3.471450e+04,
        3.880400e+04, 4.221200e+04],
       [7.450000e+01, 5.900000e+01, 8.850000e+01, ..., 2.633550e+04,
        2.839600e+04, 2.964000e+04],
       [2.735000e+02, 2.560000e+02, 3.380000e+02, ..., 3.038900e+04,
        3.285300e+04, 3.511600e+04],
       ...,
       [2.490500e+03, 2.258500e+03, 2.624500e+03, ..., 3.341550e+04,
        3.641700e+04, 4.092400e+04],
       [4.800000e+01, 3.400000e+01, 5.850000e+01, ..., 1.672900e+04,
        1.787100e+04, 2.093900e+04],
       [1.381500e+03, 1.514500e+03, 1.708500e+03, ..., 1.627075e+05,
        1.783220e+05, 2.063610e+05]]), (array([[ 1.010000e+02,  1.220000e+02,  1.330000e+02, ...,  9.917500e+03,
         1.318600e+04,  1.257200e+04],
       [-6.150000e+01, -4.500000e+01, -3.650000e+01, ..., -6.181500e+03,
        -6.153000e+03, -7.954000e+03],
       [ 2.495000e+02,  1.600000e+02,  2.690000e+02, ...,  2.506100e+04,
         2.568400e+04,  2.844800e+04],
       ...,


In [41]:
decompressed= dwt_decompress(compressed)
display(data)
display(decompressed)
print(len(decompressed))


array([[    72,    130,    110, ...,  26870,  25120,  27392],
       [     0,      0,      0, ...,  12544,  13074,  14820],
       [    11,      2,      7, ...,  10863,  11380,  10843],
       ...,
       [     0,      0,      0, ...,   7733,   8501,  10071],
       [  1246,   1424,   1387, ...,  26719,  25655,  30820],
       [    67,     26,     49, ..., 144508, 159762, 175541]], dtype=int64)

array([[7.20000e+01, 1.30000e+02, 1.10000e+02, ..., 2.51200e+04,
        2.73920e+04, 2.73920e+04],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.30740e+04,
        1.48200e+04, 1.48200e+04],
       [1.10000e+01, 2.00000e+00, 7.00000e+00, ..., 1.13800e+04,
        1.08430e+04, 1.08430e+04],
       ...,
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 8.50100e+03,
        1.00710e+04, 1.00710e+04],
       [1.24600e+03, 1.42400e+03, 1.38700e+03, ..., 2.56550e+04,
        3.08200e+04, 3.08200e+04],
       [6.70000e+01, 2.60000e+01, 4.90000e+01, ..., 1.59762e+05,
        1.75541e+05, 1.75541e+05]])

20000


In [42]:
zscore_original = np.array(zscore(data))
zscore_decompressed = np.array(zscore(decompressed))
     

print(zscore_original)        
print(zscore_decompressed)   

min_cols = min(zscore_original.shape[1], zscore_decompressed.shape[1])
zscore_original = zscore_original[:, :min_cols]
zscore_decompressed = zscore_decompressed[:, :min_cols]

rmse = mean_squared_error(zscore_original, zscore_decompressed, squared = False)
print(rmse) 

[[-0.05476221 -0.05355734 -0.0542592  ... -0.04099708 -0.04388755
  -0.04384673]
 [-0.0560654  -0.05586921 -0.05632819 ... -0.05365575 -0.05385995
  -0.05346174]
 [-0.0558663  -0.05583364 -0.05619653 ... -0.05514111 -0.05526234
  -0.05650333]
 ...
 [-0.0560654  -0.05586921 -0.05632819 ... -0.05790683 -0.05764575
  -0.05709375]
 [-0.03351293 -0.03054543 -0.03024006 ... -0.04113051 -0.04344464
  -0.04122502]
 [-0.05485271 -0.05540683 -0.05540655 ...  0.06294966  0.06757717
   0.06945687]]
[[-0.05476221 -0.05355734 -0.0542592  ... -0.04388755 -0.04384673
  -0.04384673]
 [-0.0560654  -0.05586921 -0.05632819 ... -0.05385995 -0.05346174
  -0.05346174]
 [-0.0558663  -0.05583364 -0.05619653 ... -0.05526234 -0.05650333
  -0.05650333]
 ...
 [-0.0560654  -0.05586921 -0.05632819 ... -0.05764575 -0.05709375
  -0.05709375]
 [-0.03351293 -0.03054543 -0.03024006 ... -0.04344464 -0.04122502
  -0.04122502]
 [-0.05485271 -0.05540683 -0.05540655 ...  0.06757717  0.06945687
   0.06945687]]
3.21373894736723

In [48]:
import sys
print("The given array is:",data)
print("The size of array arr is:",data.size)
print("The memorysize of each element of arr is:", data.itemsize,"bytes")
print("The memory size of numpy array arr is:",data.itemsize*data.size,"bytes")

print(sys.getsizeof(data) ," bytes")

The given array is: [[    72    130    110 ...  26870  25120  27392]
 [     0      0      0 ...  12544  13074  14820]
 [    11      2      7 ...  10863  11380  10843]
 ...
 [     0      0      0 ...   7733   8501  10071]
 [  1246   1424   1387 ...  26719  25655  30820]
 [    67     26     49 ... 144508 159762 175541]]
The size of array arr is: 4020000
The memorysize of each element of arr is: 8 bytes
The memory size of numpy array arr is: 32160000 bytes
128  bytes


In [47]:
c_data=compressed
print(sys.getsizeof(c_data) ," bytes")


56  bytes
